name: Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Package
        run: |
          VERSION="build-${{ github.run_number }}"
          ZIP_NAME="Extension_${VERSION}.zip"
          zip -r "$ZIP_NAME" . -x "*.git*" ".github*" "README.md"
          echo "V_NAME=$VERSION" >> $GITHUB_ENV
          echo "Z_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.V_NAME }}
          name: Release ${{ env.V_NAME }}
          files: ${{ env.Z_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
