name: Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: [INIT] Checkout Code
        uses: actions/checkout@v4

      - name: [ENV] Sync Timestamp and Versioning
        id: meta
        run: |
          RAW_TIME=$(date +'%y.%m%d.%H%M')
          echo "VERSION=$RAW_TIME" >> $GITHUB_ENV
          echo "ZIP_NAME=HexGem_v${RAW_TIME}.zip" >> $GITHUB_ENV

      - name: [BUILD] Production Archive
        run: |
          zip -r ${{ env.ZIP_NAME }} . \
            -x "*.git*" \
            -x ".github*"

      - name: [DEPLOY] Secure Release Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            ## [BUILD REPORT]
            - **Build Version**: `${{ env.VERSION }}`
            - **Commit Hash**: `${{ github.sha }}`
            - **Environment**: Production GHA Node
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
